### ISSUE TITLE
Cannot install vagrant-serverspec plugin

### ISSUE THREAD

**Issue by ndobbs** [vvchik/vagrant-serverspec#37] opened 2019-10-15 23:04 UTC
Vagrant aborts the installation of this plugin due to a dependency needing a newer version of ruby, 

```
vagrant version
Installed Version: 2.2.6
Latest Version: 2.2.6
```

```
vagrant plugin install vagrant-serverspec
Installing the 'vagrant-serverspec' plugin. This can take a few minutes...
Fetching: diff-lcs-1.3.gem (100%)
Fetching: rspec-expectations-3.9.0.gem (100%)
Fetching: rspec-mocks-3.9.0.gem (100%)
Fetching: rspec-3.9.0.gem (100%)
Fetching: rspec-its-1.3.0.gem (100%)
Fetching: net-telnet-0.1.1.gem (100%)
Fetching: sfl-2.3.gem (100%)
Fetching: specinfra-2.82.2.gem (100%)
Fetching: serverspec-2.41.5.gem (100%)
Fetching: os-0.9.6.gem (100%)
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

activesupport requires Ruby version >= 2.5.0.
```
```
/opt/vagrant/embedded/bin/ruby --version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin13]
```

Please let me know if I should report this bug to the vagrant team.

**Comment by 01deEng1ish** [comment] 2019-10-25 22:31
By default, it will try to install activesupport 6.0.0, which requires Ruby 2.5.0.  This can probably be fixed by adding this line to the vagrant-serverspec.gemspec file
Gem.add_runtime_dependency ‘activesupport’, ‘< 6.0.0’

The activesupport gem is actually being pulled in by rspec_html_formatter, which requests activesupport >= 4.1.4

**Comment by endemics** [comment] 2019-11-01 22:56
@vvchik Now that #38 is merged, would it be possible to cut a new gem to make installation easier? That would close this issue. Thanks!

**Comment by fasmat** [comment] 2019-11-11 15:08
Also experiencing this issue, any chance we get a new gem soon with the issue being fixed on master already?

Thanks!

**Comment by Tocyuki** [comment] 2019-11-20 05:35
I have trouble too from this issue.
Do you have any temporary solution with this issue?

**Comment by 01deEng1ish** [comment] 2019-11-22 13:15
These workaround I use:
1. Attempt installation of plugin
2. After install fails, modify the gemspec file, ~/.vagrant.d/gems/2.4.4/specifications/vagrant-serverspec-1.3.gemspec on my system, and manually add activesupport < 6.0.0 dependency
3. Install serverspec plugin, which works for me at this point.

**Comment by NicolaiMogensen** [comment] 2020-01-03 13:03
On my Windows x64 system the serverspec-1.3.gemspec file is never created, so i can't use @01deEng1ish workaround. Even if i upgrade Ruby to > 2.5.0 the command `vagrant plugin install vagrant-serverspec` still fails with `activesupport requires Ruby version >= 2.5.0.`

ruby --version 
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]`

**Comment by becw** [comment] 2020-01-17 19:44
I wasn't able to modify the gemspec file after the install failed -- Vagrant hadn't downloaded a gem for me to modify.

Here's the end to end workaround that worked for me:

```sh
# Clone this repository locally
git clone git@github.com:vvchik/vagrant-serverspec.git

# Build the gem
cd vagrant-serverspec
gem build vagrant-serverspec.gemspec

# Install the vagrant plugin from the local gem path
# (use your own local absolute path to the gem)
vagrant plugin install /Users/becw/repos/vagrant-serverspec/vagrant-serverspec-1.3.gem
```

**Comment by vvchik** [comment] 2020-01-20 02:18
I've pushed the latest version to RubyGems.
should work now, can you guys check?

**Comment by endemics** [comment] 2020-01-20 02:22
> I've pushed the latest version to RubyGems.
> should work now, can you guys check?

Hi @vvchik thanks for that.

Was it gem v1.5? It is marked as "yanked" from RubyGems

**Comment by vvchik** [comment] 2020-01-21 06:01
No 1.5.0, I've pushed 1.5 first, but it does not follow semver, so I decided to reupload with new version number.

**Comment by endemics** [comment] 2020-01-21 08:30
@vvchik I can confirm that v1.5.0 works fine for me (vagrant 2.2.6, macos Mojave 10.14.6, Virtualbox 6.0.16).

Thanks a lot!

**Comment by fasmat** [comment] 2020-01-21 09:11
Solved the issue for me too

**Comment by vvchik** [comment] 2020-01-21 17:36
Thanks, guys for confirmation. I will close this issue then.
I enabled GitHub actions so upload of new versions will happen automatically on master merge now.

**Closed by vvchik** 2020-01-21 17:36 UTC
